### ISSUE TITLE
Bluetooth functionality

### ISSUE THREAD

**Issue by n1md4** [klutchell/balena-homeassistant#210]
More a feature request than an issue persay.  I would like to add bluetooth functionality to my home assistant installation.

I have added a dbus label to the homeassistant service, but don't know how to install bluez to the container host.

https://forums.balena.io/t/home-assistant-bluetooth-integration/366138

**Comment by klutchell** [comment]
Good idea, we could probably copy some of the logic from https://github.com/balena-labs-projects/bluetooth

**Comment by klutchell** [comment]
@n1md4 after you added the DBus label, did you set the required env var?

```
# DBUS is required for bluetooth-agent
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
```

It [looks like the python package bluez-dev](https://github.com/search?q=repo%3Ahome-assistant%2Fdocker-base%20bluez&type=code) may already be in the base images so hopefully we don't need to install any extra packages?
