### ISSUE TITLE
PS4 integration

### ISSUE THREAD

**Issue by n1md4** [klutchell/balena-homeassistant#230]
Not an issue with your build, but thought this is the best place to ask about Balena and Home Assistant integrations :) 

I would like to integrate the PS4 to HA.  I have the 2nd screen app installed and working on my phone, but HA integration fails, can't see any logs on either HA or the app.

https://www.home-assistant.io/integrations/ps4

> The PlayStation 4 integration requires the use of privileged ports during configuration to work correctly, specifically UDP port 987 and TCP port 997. Depending on your OS of your Home Assistant instance, you may need to allow usage of privileged ports manually.

and 

> When running Home Assistant using Docker, make sure that the Home Assistant container is discoverable by the PS4. This can be achieved by ensuring that the Home Assistant container uses the `host` network driver (by passing `--net=host` to the container when creating, or adding `network_mode: "host"` to your compose file when using `docker-compose`).

I tried setting the homeassistant service to use the host network mode and it broke.  Would appreciate any thoughts you might have about this issue.

**Comment by klutchell** [comment]
Hey @n1md4, I haven't tried this integration myself, but I try to help a bit.

If you enable host networking, the [existing port mapping](https://github.com/klutchell/balena-homeassistant/blob/ced94aa22578be94b29cc1345db374ab353940f7/docker-compose.yml#L7-L8) is ignored so your homeassistant will be listening on port 8123 unless you change your [server_port](https://www.home-assistant.io/integrations/http/#server_port) setting.

Hopefully your HA was actually running but just not on the port you expected. If you confirm it works on 8123 you can always change it to 80 and restart.

Privileged ports should not be an issue that I'm aware of when using the official container.

**Comment by n1md4** [comment]
You're quite right!
