### ISSUE TITLE
Upgrading Home Assistant Image in older image

### ISSUE THREAD

**Issue by jsanctum** [klutchell/balena-homeassistant#688]
What's the easiest way to update the Home Assistant image in an already deployed Balena instance?

**Comment by jsanctum** [comment]
Thanks @klutchell, I'm presuming any integrations and automations already in the existing HA instance would be reset and have to be added again after this push?

**Comment by klutchell** [comment]
Correct, your data automatically persists across updates in [these volumes](https://github.com/klutchell/balena-homeassistant/blob/ec1f4eb5672b5d80d8bf790dbf9dd98ed61e3bd6/docker-compose.yml#L200-L213).

**Comment by Jaxom99** [comment]
Hi @klutchell , sorry for digging this up, but I don't quite get your final answer : if the data persists, do I have to re-add it to HA manually ? or all settings/integrations would be already picked up by the new HA version? maybe @jsanctum you can share how it went for you ?
thanks in advance 😺
